languageCode: "en-gb"
uglyURLs: false
title: "Rioxx: The Research Outputs Metadata Schema"
author: "Paul Walk"
copyright: "This website and blog are licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-sa/3.0/deed.en_GB'>Creative Commons Attribution-ShareAlike 3.0 Unported License</a>"
enableRobotsTXT: false
metaDataFormat: "yaml"
theme: "rioxx"
enableGitInfo: false
disablePathToLower: true
taxonomies:
  tag: "tags"
  topic: "topics"
  category: "categories"
permalinks:
  # post: "/:year/:month/:day/:title/"
  # page: "/:title/"
params:
  tagline: "Rioxx: The Research Outputs Metadata Schema"
  pageSize: "10"
  AuthorName: "Paul Walk"
  showPageStatusTagsOnLiveSite: true
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: pygments
    tabWidth: 4